### ISSUE TITLE
Appropiately self-heal on reorgs

### ISSUE THREAD

**Issue by Evalir** [Blobscan/blobscan-indexer.rs#19]
_This is a bit of a long shot issue, mostly for when things are already set in prod._

Right now, the indexer is not really resilient to reorgs. While rare, we should make sure it can detect them and self-heal.

**Comment by PJColombo** [comment]
Hey @Evalir, we should look into this! :eyes:

Could you share your strategy for addressing this issue? Perhaps something like having a safety reorganization margin and indexing blocks up to that point?

**Comment by Evalir** [comment]
Hmm yeah, frankly I'm not super knowledgeable on how reliable production systems like Polygonscan (which has to deal with big reorgs frequently :D) do it; but the most straightforward strategy is a having a margin to the tip. 

Off the top of my head (haven't thought deeply about this) I assume another viable strategy would be to check the new block hash against the previous one to see if it hashes back to the received block (essentially, check that N-1 indeed precedes block N). If it doesn't match, a reorg happened somewhere. I guess this strategy could let the indexer be as up-to-date as possible while being able to backtrack reorgs.

**Comment by PabloCastellano** [comment]
Some hours ago the indexer is crashed while trying to write to postgres. A validator has sent two blocks proposals (one could slash the validator for it). Since we consider block numbers unique in the db schema, postgres complains when it tries to insert another block with the same number, and keeps retrying, so that newer blocks are not processed.

@PJColombo and I have spoken today about this issue and we are prioritizing it. It is affecting blobscan.com too (shows last indexer was 4 hours ago).

Here are the relevant transactions:

- [Block 1 for slot 62506](https://light-beaconchain-explorer.dencun-devnet-8.ethpandaops.io/slot/0x823a212fd04458c2eed5a576786a3cfa7ad79a6f431448f0f04e60bf7cddd978)
- [Block 2 for slot 62506](https://light-beaconchain-explorer.dencun-devnet-8.ethpandaops.io/slot/0xb833820b0e2c4dd3aca522a7b661120ab329e7770ee4bb4e6c8ee00e17a2f1b3)
- [Slot 62507](https://light-beaconchain-explorer.dencun-devnet-8.ethpandaops.io/slot/62507)

From there we can see that the parent hash of slot 62507 coincides with only one of the two blocks in slot 62506. (there are no slashers running in devnet-8 at the moment so that is why they are both shown as correct (finalized).

I wonder if simply adding a check of the parent hash is enough to appropriately self-heal and discard forked blocks. @Evalir what do you think? do you think this is enough?

**Comment by pk910** [comment]
First of all, I really like that you've linked my explorer to demonstrate the problem ♥
There is unfortunately a small issue, which currently shows all finalized blocks as "orphaned" in the block details. 
Actually, [block 2](https://light-beaconchain-explorer.dencun-devnet-8.ethpandaops.io/slot/62506) in the example above is the canonical block and shouldn't be shown as orphaned. That's a display issue only, it's correct in the backend DB.

I gonna share some thoughts I had in mind when implementing the indexer for the light-beaconchain-explorer.
It's probably not 1:1 transferable to blobscan, but might help to improve your indexer too :)

There are two possible indexing strategies. 
1. Index the canonical chain only (I think that's the strategy you're currently trying to achieve.)
  The indexer follows the [block event stream](https://ethereum.github.io/beacon-APIs/#/Events/eventstream).
  For each block event the appropriate [block header](https://ethereum.github.io/beacon-APIs/#/Beacon/getBlockHeader) is loaded.
  The parent root within the block header is checked against the block root of the last block the indexer received earlier.
  If it does not match, discard all blocks that were previously indexed up to the slot number of the incoming block.
  Do indexer logic for the new block and set it as last received.
  \
  The event stream will basically do all the reorg logic for you.
  When a reorg happens, there are block events emitted for all reorganized blocks in correct order - so from indexer perspective it just looks like  going back x blocks, and receiving x new blocks one by one.
  \
  By discarding previously indexed blocks when going back, you could even keep your primary key on the slot number.
  \
  Note that this strategy don't necessarily gives you the canonical chain. It's just the canonical chain from the connected CL nodes perspective. If the client is forked off on a non finalizing chain, you're following that chain and you'll hit a large reorg at some time.
  
2. Index the whole chain including all orphaned blocks
  That's the much more complex strategy. I've tried to achieve that via a similar way as before, but got into big troubles with handling the orphaned blocks properly. Especially when you try to grab events from multiple CL nodes (which is necessary if you want to track orphaned blocks reliably), its near impossible to get a consistent view of the canonical chain. There will be situations where the connected clients don't agree with each other and send out different head events.\
  For that reason, I'm not even trying to do any persistent canonical/orphaned detection before finalization. Finalization checkpoints are the only reliable way to determinate the canonical chain. Actually I'm not indexing unfinalized blocks at all, because I cannot be sure what kind of processing is needed (my orphaned processing is different than for canonical blocks).
  \
  To achieve this indexing scenario, the event streams from all clients are fetched as before. When a new block is received from any client, it is just dumped into a central cache that keeps track of all recent blocks from all nodes.\
  The cache is organized by block root and slot number. When the same block is received from multiple clients it gets stored once only and appropriate block header/bodies are loaded only once too (basically from the first node that sees them).
  \
  In addition to the block events, the indexer also subscribes to finalized_checkpoint events.
  The indexer keeps track of that checkpoint globally. Whenever one of the clients receives a higher checkpoint, the indexer logic is triggered.
  \
  With the checkpoint, the indexer can now reliable determinate the canonical chain by iterating through the cached blocks.
  It starts with the block referenced in the checkpoint and iterates back via the parent root property of each block.
  The indexer logic is applied on all blocks on the way (these are all canonical blocks).
  \
  When finished, all remaining cached blocks with slot < checkpoint_slot are orphaned blocks and are now indexed as orphaned blocks as well.
  \
  This approach can lead to a high memory consumption during long non-finality time. I'm mitigating that by dumping cached block bodies into a separate database after some time (when >5 epochs are unfinalized). I have to store them somehow, because orphaned blocks are removed from CL nodes after finalization, so I can't fetch them anymore afterwards.
  \
  To show "live data" in my explorer, the unfinalized blocks are directly fetched from the indexer cache. That obviously makes these data views a lot more complex (fetching data from cache & db and combining results).

I've been using the first strategy and switched over to the second more complex strategy a week ago.
It looks like it's working quite well, but I haven't been able to see how it behaves in a real chain split scenario with long un-finality yet (devnet-8 is working too well :D)

**Comment by PJColombo** [comment]
TODO list for achieving first indexing strategy:

**Indexer**

- [ ] Add logic to check if current fetched block is a reorg or not (we can do that by keeping the previous indexed block and check if the block parent root hash of it and the current fetched one matches).

**API**

- [ ] Add new boolean param to index endpoint body that indicates if the current block is a re-org or not. If it is then we execute the correspondent logic which is moving all the transactions of the blocks between the re-org one and the latest one to the `transaction_forks` table.

**DB**

- [ ] Create a new Prisma model called `TransactionFork` which will have the following fields: `hash` (fk), `index` and `blockHash` (fk), `insertedAt` and `updatedAt`.
- [ ] Make block number field in block model not unique.
